### ISSUE TITLE
Нужна помощь 

### ISSUE THREAD

**Issue by Kymatozni4ek** [fcaronte/KingInstaller#1]
Помогите пожалуйста разобраться. Что я не так делаю 

https://user-images.githubusercontent.com/127259981/223575574-564122c2-6b02-424c-9573-241c31c82984.mp4

**Comment by fcaronte** [comment]
> Помогите пожалуйста разобраться. Что я не так делаю 
> 
> https://user-images.githubusercontent.com/127259981/223575574-564122c2-6b02-424c-9573-241c31c82984.mp4
> 
> 

The third installer should not exist, you need to use the default installer with the arrow icon (the one in the center in your video)

**Comment by Kymatozni4ek** [comment]
> 

Подскажите как его удалить? Или как все сделать? С меня донат.
