### ISSUE TITLE
Not working on Pixel 7 Pro

### ISSUE THREAD

**Issue by JhoGraessl** [fcaronte/KingInstaller#11]
When i install apps through KingInstaller, it tells me that the apps are installed from KingInstaller and not from the Google Play Store

**Comment by fcaronte** [comment]
> When i install apps through KingInstaller, it tells me that the apps are installed from KingInstaller and not from the Google Play Store

Yes is normal is how should work, if you don't see the app you need to read the main readme or closed issue where I explain how to fix for pixel phone
