### ISSUE TITLE
No benefit on P6P

### ISSUE THREAD

**Issue by AAMAA** [fcaronte/KingInstaller#2]
First Thanks for this project and for all developing.
I have tested the app on P6P but unfortunately still the system not recognize the app. The test was to install Fermata but it's still not appear on the android Auto.
Any support and help to get it work will be much appreciated.

**Comment by fcaronte** [comment]
What's phone is p6p? Be sure to enable "unknown source" inside the development mode of android auto or will never show it

**Comment by AAMAA** [comment]
Thanks for your reply.
It's Google Pixel 6 Pro.
The unknown source is enabled, the app was working in the last 2 months without any single issue. Some user's suggested to install it using King installer but there is no changes.

**Comment by fcaronte** [comment]
Have you try to remove fermata + fermata control and then reinstall from scratch with last version? Pixel should not need for the Oppo trick and should work using kinginstaller normally but you are not the first pixel user with problem but other pixel user can use it normally so I can't understand what's could be the problem

**Comment by AAMAA** [comment]
I have tried this

**Comment by fcaronte** [comment]
Today I try few minutes on my friend Pixel 7 and i can confirm this issue, but is not something related to kinginstaller but probably Google add new block, the strange things is that is not happen to all pixel phone, if you discover something new, update me

**Comment by AAMAA** [comment]
> Today I try few minutes on my friend Pixel 7 and i can confirm this issue, but is not something related to kinginstaller but probably Google add new block, the strange things is that is not happen to all pixel phone, if you discover something new, update me

It's a common problem now with many Brand's i guess, I'm still trying, will let you know If there is any success.
Too to please share if you got something.

**Comment by tjuanma** [comment]
Same here with Pixel 7.
Impossible to make fermata visible anymore. Tryied also to patch with root from AA AIO Tweaker and same result.

Any new on your sides?

**Comment by fcaronte** [comment]
If you have root you can try with this. Read the instructions because I don't test personally
https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked

**Comment by tjuanma** [comment]
> If you have root you can try with this. Read the instructions because I don't test personally https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked

just installed but I don't understand how to install fermata from this AA launcher

**Comment by fcaronte** [comment]
As I known fermata just have a root method using lposed, then the magisk module work similar to the fermata auto method but for the others app to, I think apk should be installed as PlayStore using kinginstaller and then enable the magisk module to show app on Android auto, try read instructions on kinginstaller page because I don't know exactly step needed

**Comment by overbit** [comment]
The issue is that even if apks are installed through KingInstaller in the app details it states Installed from KingInstaller instead of Google Play Store

**Comment by fcaronte** [comment]
> The issue is that even if `apk`s are installed through KingInstaller in the app details it states Installed from KingInstaller instead of Google Play Store

Nope, unfortunately is not that problem, on other android 13 phone have same things but work correctly too.

![Screenshot_20230703-112955.png](https://github.com/fcaronte/KingInstaller/assets/26366403/721473c7-1488-4f40-9a19-bb80ceeba502)

**Comment by AAMAA** [comment]
Thanks.
It's appeared now in the android auto app list, i will try if i can play video once i get my Car.

**Comment by AAMAA** [comment]
> Can you try to install this package installer version and then try again to reinstall from scratch fermata auto using kinginstaller?
> 
> https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-13-8768315-release/package-installer-13-8768315-android-apk-download/

Thanks man it's working now. Without root all is ok.
Thanks a lot.

**Comment by fcaronte** [comment]
Seem you can use and reinstall the same apk version you just have

**Comment by AAMAA** [comment]
> Seem you can use and reinstall the same apk version you just have

I have installed 1.9.1 first worked perfectly, and the i installed 1.9.2 also using kinginstaller. Both versions are ok

**Comment by JhoGraessl** [comment]
Tried it today, this method is sadly not working anymore

**Comment by fcaronte** [comment]
> Tried it today, this method is sadly not working anymore

Do you have stock Google pixel? Do you install from ApkMirror? If you go to Google PackageInstaller in the app will see the "uninstall update" under the 3dot menù on top right corner?

**Comment by JhoGraessl** [comment]
> > Tried it today, this method is sadly not working anymore
> 
> Do you have stock Google pixel? Do you install from ApkMirror? If you go to Google PackageInstaller in the app will see the "uninstall update" under the 3dot menù on top right corner?

Yes, I have a stock pixel
I got the exact version you posted in here
Yes I do

I installed the version and it still installs the app as "installed from Kinginstaller"

**Comment by fcaronte** [comment]
> > > Tried it today, this method is sadly not working anymore
> > 
> > Do you have stock Google pixel? Do you install from ApkMirror? If you go to Google PackageInstaller in the app will see the "uninstall update" under the 3dot menù on top right corner?
> 
> Yes, I have a stock pixel
> I got the exact version you posted in here
> Yes I do
> 
> I installed the version and it still installs the app as "installed from Kinginstaller"

But you follow other steps too? Unlock development option and enable unknown source, what are you try to install

**Comment by JhoGraessl** [comment]
> > > > Tried it today, this method is sadly not working anymore
> > > 
> > > Do you have stock Google pixel? Do you install from ApkMirror? If you go to Google PackageInstaller in the app will see the "uninstall update" under the 3dot menù on top right corner?
> > 
> > Yes, I have a stock pixel
> > I got the exact version you posted in here
> > Yes I do
> > 
> > I installed the version and it still installs the app as "installed from Kinginstaller"
> 
> But you follow other steps too? Unlock development option and enable unknown source, what are you try to install

Yes, on my second phone (Huawei P30 Pro) it works just fine. I'm trying to install this: https://github.com/agronick/aa-torque/tree/master

**Comment by fcaronte** [comment]
Thanks to share this app, I missing it and I was stuck with old limited version. I'll try tomorrow. About your problems I don't know other this to suggest, be sure to remove all flag in the kinginstaller app, the Google PackageInstaller installer try to use the stock apk installer and not kinginstaller . Then if you have A14 you need to use A14 apk version. And if you are on A13 try use the 13-somenumer version instead of the clean 13 version. As today we know only this trick for pixel and seem to work
