### ISSUE TITLE
How does the app work?

### ISSUE THREAD

**Issue by ABJ4403** [fcaronte/KingInstaller#26]
PS: My message might not be seen cuz GitHub banning my account, so might be useless for me to even ask this in the first place

so uhh, is all this app do just ```bash
pm install -i com.android.vending base.apk``` ?

**Comment by ABJ4403** [comment]
Just like what i ofc expected aint seein that, if you se it say fuck github, gitlab good (at this point if you can go past gitlab registration, its much much better than github hectic robot deciding banning garbage trash)

**Comment by jksekai** [comment]
I can see it
