### ISSUE TITLE
Pixel 6a  ha dejado de funcionar

### ISSUE THREAD

**Issue by ramon165** [fcaronte/KingInstaller#7]
Desde hace una semana ha dejado de funcionar kinginstaller.  Actualice una apk . Y desapareció de Android auto.  La versión de Android es 13. He intentado instalar la anterior apk y ya no sale el el menú de Android auto.  Tengo otro móvil con Android 11  un xiaomi A3 y sigue funcionando sin problemas. Creo que el problema es pixel. Tiene la última actualización de marzo. 2023.

**Comment by fcaronte** [comment]
Yes unfortunately last pixel update broke something and as now we don't have info on how to fix, do your test and if you find a working trick let's say us

**Comment by tjuanma** [comment]
> Yes unfortunately last pixel update broke something and as now we don't have info on how to fix, do your test and if you find a working trick let's say us

Hi, any new about this? Impossible to install fermata on Pixel 7 :S

**Comment by fcaronte** [comment]
Nope, no info. Unfortunately I haven't this phone

**Comment by fcaronte** [comment]
Can you try to install this package installer version and then try again to reinstall from scratch fermata auto using kinginstaller?

https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-13-8768315-release/package-installer-13-8768315-android-apk-download/

**Comment by fcaronte** [comment]
Confirmed working and seem you can use and reinstall the same apk version you just have
