### ISSUE TITLE
license missing?

### ISSUE THREAD

**Issue by IzzySoft** [fcaronte/KingInstaller#9]
It looks like you forgot to specify the license this app falls under. Could you please clarify? If you simply did not yet choose, may I suggest to pick one approved as F/LOSS by OSI/FSF, as indicated by [this list](https://spdx.org/licenses/)? Thanks in advance!

**Comment by fcaronte** [comment]
What do you mean with this? What license?

**Comment by IzzySoft** [comment]
I mean, the source is in the open, yes – but there's no [license](https://en.wikipedia.org/wiki/License) declared on what is considered "permitted use".

> A license (or licence) is an official permission or permit to do, use, or own something (as well as the document of that permission or permit).

If there is no license, a project is usually considered "all rights preserved". It is considered free/libre open source or [F/LOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) if a free/libre license applies. Unfortunately, there's a risk of getting sued for non-permitted use if it's not clear what terms apply (which indeed happened already more than once – not saying it would apply to you of course), so F/LOSS folks like me prefer to make sure first.

Just to clarify: no offense meant at all – as indicated this is rather asking for clarification.

> open source fork from annexhack project

which unfortunately does not declare a license either – I see the problem now. So let me raise the question with Dimitriy then – and maybe you could then adapt what he chooses.

Speaking of fork: I see your changes [where integrated with "upstream"](https://gitlab.com/annexhack/king-installer/-/commit/2d35b44d454a79dfa9c20e959e1f3b7c3249e729). Would you then recommend using "the original" instead – or what should one consider when making this decision?

PS: Thanks a lot for your swift reply, much appreciated!

**Comment by IzzySoft** [comment]
For reference: I've raised the question with Dimitrij [here](https://gitlab.com/annexhack/king-installer/-/issues/1).

**Comment by fcaronte** [comment]
> For reference: I've raised the question with Dimitrij [here](https://gitlab.com/annexhack/king-installer/-/issues/1).

Hi, I see as today no replies from the original Dev, so here I decided to choose the "GNU GENERAL PUBLIC LICENSE v3" and we can close this issue

**Comment by IzzySoft** [comment]
Wonderful, thanks! May I also ask you to always [increase `versionCode`](https://github.com/fcaronte/KingInstaller/blob/master/app/build.gradle#L21) when preparing a new release? That's what Android uses to tell versions apart – and your app still has that on `1`, so technically there's only a single version existing.

I've just added your app to my repo now, so it should [show up here](https://apt.izzysoft.de/packages/com.example.kinginstaller/) with the next sync around 6 pm UTC. Updates will be fetched automatically within 24h of your making them available – but update notifications will only reach devices if `versionCode` was increased :wink:

Now, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme. And if you have some screenshots I should add to the listing, please let me know!

**Comment by fcaronte** [comment]
> Wonderful, thanks! May I also ask you to always [increase `versionCode`](https://github.com/fcaronte/KingInstaller/blob/master/app/build.gradle#L21) when preparing a new release? That's what Android uses to tell versions apart – and your app still has that on `1`, so technically there's only a single version existing.
> 
> I've just added your app to my repo now, so it should [show up here](https://apt.izzysoft.de/packages/com.example.kinginstaller/) with the next sync around 6 pm UTC. Updates will be fetched automatically within 24h of your making them available – but update notifications will only reach devices if `versionCode` was increased :wink:
> 
> Now, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme. And if you have some screenshots I should add to the listing, please let me know!

Ok done! Try to check if you like, and yes I understand about version code if will be some new version 👍🏻

**Comment by IzzySoft** [comment]
Looks wonderful, thanks! And will stop leading to a 404 as soon as the sync is through :smile:
